"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

import Shell from "@/components/Shell";
import { HoneypotSummary, formatDate, request } from "@/lib/api";

export default function HoneypotPage() {
  const [data, setData] = useState<HoneypotSummary | null>(null);
  const [error, setError] = useState("");
  const [syncing, setSyncing] = useState(false);
  const router = useRouter();

  const load = useCallback(async () => {
    try {
      setData(await request<HoneypotSummary>("/portal/honeypot/summary"));
      setError("");
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Unable to load honeypot intelligence");
    }
  }, []);

  useEffect(() => {
    if (!localStorage.getItem("access_token")) {
      router.push("/login");
      return;
    }
    void load();
    const timer = window.setInterval(() => void load(), 15000);
    return () => window.clearInterval(timer);
  }, [load, router]);

  async function sync() {
    setSyncing(true);
    try {
      await request("/integrations/honeypot/sync", { method: "POST" });
      await load();
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Synchronization failed");
    } finally {
      setSyncing(false);
    }
  }

  const integration = data?.integration;

  return (
    <Shell>
      <div className="header">
        <div>
          <div className="eyebrow">External threat intelligence</div>
          <h1>Honeypot intelligence</h1>
          <p className="subtitle">
            Real attacks collected by the deployed SSH, HTTP, HTTPS and FTP honeypots.
          </p>
        </div>
        <div className="header-actions">
          <span className={`status-dot ${integration?.status ?? "unknown"}`}>
            API {integration?.api_connected ? "online" : "offline"}
          </span>
          <button className="secondary" onClick={sync} disabled={syncing}>
            {syncing ? "Synchronizing…" : "Sync now"}
          </button>
          {integration?.grafana_url && (
            <a className="button-link" href={integration.grafana_url} target="_blank" rel="noreferrer">
              Open Grafana SOC Console
            </a>
          )}
        </div>
      </div>

      {error && <div className="card error">{error}</div>}

      <div className="grid metrics-grid">
        <Metric label="Attack Events" value={integration?.total_events ?? 0} detail="Observed by deployed honeypots" />
        <Metric label="Unique Attackers" value={integration?.total_attackers ?? 0} detail="External source IP profiles" />
        <Metric label="SOC Alerts" value={integration?.total_alerts ?? 0} detail="Generated by honeypot analytics" />
        <Metric label="Critical Alerts" value={data?.alerts_by_severity.critical ?? 0} detail="Immediate investigation" tone="critical" />
        <Metric label="High Alerts" value={data?.alerts_by_severity.high ?? 0} detail="High-risk attacker activity" />
        <Metric label="Last Sync" value={integration?.last_success_at ? "Online" : "Never"} detail={formatDate(integration?.last_success_at ?? null)} tone={integration?.api_connected ? "healthy" : "critical"} />
      </div>

      <section className="section card">
        <div className="section-heading"><div><h2>Attack volume by service</h2><p>Live totals reported by the deployed SOC API.</p></div></div>
        <div className="service-grid">
          {Object.entries(data?.by_service ?? {}).map(([name, count]) => (
            <div className="service-card" key={name}><span>{name}</span><strong>{count.toLocaleString()}</strong></div>
          ))}
        </div>
      </section>

      <div className="content-grid">
        <section className="section card">
          <div className="section-heading"><div><h2>Recent attack feed</h2><p>Normalized events synchronized from the remote honeypot.</p></div></div>
          <div className="table-wrap"><table><thead><tr><th>Severity</th><th>Activity</th><th>Attacker</th><th>Location</th><th>Time</th></tr></thead>
          <tbody>{data?.recent_events.length ? data.recent_events.map((event) => (
            <tr key={event.id}><td><span className={`badge ${event.severity.toLowerCase()}`}>{event.severity}</span></td><td><strong>{event.event_type}</strong><div className="table-subtitle">{event.service} · {event.attack_type} · Risk {event.risk_score}</div></td><td>{event.source_ip}<div className="table-subtitle">User: {event.username ?? "—"}</div></td><td>{String(event.geo.country ?? "Unknown")}<div className="table-subtitle">{String(event.geo.city ?? "")}</div></td><td>{formatDate(event.observed_at)}</td></tr>
          )) : <tr><td colSpan={5} className="empty-state">No honeypot events synchronized yet.</td></tr>}</tbody></table></div>
        </section>

        <section className="section card integration-card">
          <h2>Top attackers</h2>
          {data?.top_attackers.map((attacker) => (
            <div className="attacker-row" key={attacker.id}><div><strong>{attacker.source_ip}</strong><span>{attacker.city ?? "Unknown"}, {attacker.country ?? "Unknown"}</span></div><div className="risk-score">{attacker.risk_score}</div></div>
          ))}
          <div className="integration-time">Last successful sync: {formatDate(integration?.last_success_at ?? null)}</div>
          {integration?.last_error && <div className="inline-error">{integration.last_error}</div>}
        </section>
      </div>

      <section className="section card">
        <div className="section-heading"><div><h2>Critical and high honeypot alerts</h2><p>Evidence remains preserved in the deployed honeypot SOC.</p></div></div>
        <div className="table-wrap"><table><thead><tr><th>Severity</th><th>Alert</th><th>Source IP</th><th>MITRE</th><th>Time</th></tr></thead>
        <tbody>{data?.critical_alerts.length ? data.critical_alerts.map((alert) => (
          <tr key={alert.id}><td><span className={`badge ${alert.severity}`}>{alert.severity}</span></td><td><strong>{alert.title}</strong><div className="table-subtitle">{alert.rule_id}</div></td><td>{alert.agent_ip ?? "—"}</td><td>{alert.mitre_techniques.join(", ") || "Unmapped"}</td><td>{formatDate(alert.event_timestamp)}</td></tr>
        )) : <tr><td colSpan={5} className="empty-state">No high-priority honeypot alerts synchronized yet.</td></tr>}</tbody></table></div>
      </section>
    </Shell>
  );
}

function Metric({ label, value, detail, tone }: { label: string; value: string | number; detail: string; tone?: string }) {
  return <div className={`card metric-card ${tone ?? ""}`}><div className="label">{label}</div><div className="metric">{typeof value === "number" ? value.toLocaleString() : value}</div><div className="metric-detail">{detail}</div></div>;
}
